version: "3.7"
services:
    app:
        build:
            args:
                user: devil
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: dockerized-laravel-max-ltd-app
        container_name: dockerized-laravel-max-ltd-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - dockerized-laravel-max
    db:
        image: mysql:8.0
        container_name: dockerized-laravel-max-ltd-mysql
        restart: unless-stopped
        ports:
            - ${DB_PORT_EXTERNAL}:${DB_PORT}
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - dockerized-laravel-max
    nginx:
        image: nginx:alpine
        container_name: dockerized-laravel-max-ltd-nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - dockerized-laravel-max
networks:
  dockerized-laravel-max:
      driver: bridge
